GET http://localhost:1235/destinations

###
GET http://localhost:1235/destinations?slug=weekend

###
GET http://localhost:1235/destinations/1c694f60-25f8-46a4-87c5-48c179595fab
###
POST http://localhost:1235/destinations
Content-Type:  application/json
###
DELETE http://localhost:1235/destinations/1fde4080-4ced-460a-a966-6efb1897ac11

###
PATCH http://localhost:1235/destinations/1c694f60-25f8-46a4-87c5-48c179595fab
Content-Type:  application/json

{
  "slug": "chiclayo"
}

